services:
  mobility_api:
    build: .
    command:
      - --port=8080
      - --log-level=info
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
